project:
  type: website

website:
  title: "Allan Spadini"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/allanspadini
      - icon: twitter
        href: https://twitter.com/allanspadini
format:
  html:
    theme: lux
    css: styles.css



