project:
  type: website
  output-dir: docs

website:
  title: "Allan Spadini"
  favicon: favicon.png
  google-analytics: "G-GYGVDM95HH"
  navbar:
    right:
      
      - text: Aprender Geofísica
        menu: 
        - text: Sísmica
          href: https://www.youtube.com/watch?v=evYh-mtvhQQ&list=PLJL6CiUP6VydBjCqH_TiUcERljDZm38hW&pp=gAQB
        - text: Geoelétrica
          href: https://www.youtube.com/watch?v=5yVfJ6UHPRo&list=PLJL6CiUP6VydHHBTQXaWONN45NfZmxVUz&pp=gAQB
      - text: Apps
        menu:
        - text: Geo Cat Eye
          href: https://allanspadini-geocateye-geocateye-dvdnbe.streamlit.app/
      - text: Livros
        menu:
        - text: Séries temporais com Prophet
          href: https://www.casadocodigo.com.br/products/livro-series-temporais-prophet

      - text: Monitor da Terra
        menu:
        - text: Terremotos no mundo
          href: https://allanspadini.com/mapa_terremotos/
        
      - icon: github
        href: https://github.com/allanspadini
      - icon: twitter
        href: https://twitter.com/allanspadini

      - about.qmd
      
format:
  html:
    theme: darkly
      
    css: styles.css



